# Autogenerated wrapper script for Heptagon_jll for x86_64-w64-mingw32
export heptc

JLLWrappers.@generate_wrapper_header("Heptagon")
JLLWrappers.@declare_executable_product(heptc)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        heptc,
        "bin\\heptc.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
